---
name: Test

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inko-lang/inko:latest
    steps:
      - run: microdnf install --quiet --assumeyes tar git
      - uses: actions/checkout@v3
      - run: inko --version
      - run: inko test
